name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build_mac_release:
    name: Build caniput for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: caniput
            asset_name: caniput-macos
    steps:
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: |
        brew install rustup
        rustup-init -y --default-toolchain nightly
    - name: Build
      run: cargo build --release --locked

  build_linux_release:
    name: Build caniput for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: caniput
            asset_name: caniput-linux64
    steps:
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked

